### ISSUE TITLE
User not created on Signup.

### ISSUE THREAD

**Issue by stemil23** [edgedb/nextjs-edgedb-auth-template#19]
I do not believe this code is working presently.
`await client.query(`
        INSERT User {
          name := '',
          email := '${emailData?.email}',
          userRole := 'user',
          identity := (global ext::auth::ClientTokenIdentity)
        }
      `);`

New email+password signup does not create a User.

**Comment by stemil23** [comment]
Actually it was an issue with the access policies.
I made the following change:
```
    access policy current_user_has_full_access
      allow all
      using (.id ?= global current_user.id);
    access policy admin_has_full_access
      allow all
      using (global current_user.userRole ?= Role.admin);
    access policy everyone_insert_only
      allow insert;
```

to:
```
    access policy admin_full_access
      allow all
      using (global current_user.userRole ?= Role.admin);
    access policy self_full_access
      allow all
      using (global current_user.id ?= .id);
    access policy everyone_read
      allow select;
    access policy allow_insert
      allow insert; 
```

And now Users are visible in EdgeDB UI and the Dashboard application works.

**Comment by beerose** [comment]
I just tested the template, and it appears that new users are being created properly. The current access policies allow everyone to insert users, so the authentication callback should function correctly. However, we cannot permit everyone to select users, as this could lead to unauthorized access to user data.

You might not see users in the EdgeDB UI due to the settings. You can disable applying access policies for the EdgeDB UI by setting `apply_access_policies` to `false`:
![Screenshot 2024-10-17 at 14 34 55](https://github.com/user-attachments/assets/59b5071d-56f3-4831-8c84-e8f0acfdac61)

Closing this issue, but let me know if this is still a problem!

**Comment by stemil23** [comment]
Thanks. Appreciate this.
